ARG NODE_VERSION="20.9.0"
ARG PNPM_VERSION="8.15.8"

##
# Create base image with pnpm installed 
##

FROM node:${NODE_VERSION}-alpine as jkomyno-pnpm
LABEL jkomyno/pnpm-monorepo-example.name=pnpm

RUN apk add git
RUN apk add --no-cache --upgrade grep
RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store \
  npm i -g pnpm@${PNPM_VERSION}

WORKDIR /app

COPY ["./*.json", "./*.yaml", "./"]
